### ISSUE TITLE
how to only run cases that have not been executed or the last execution record is failed

### ISSUE THREAD

**Issue by CamilleDZ** [lczub/TestLink-API-Python-client#100]
Dear Dev,
    I use getTestCasesForTestPlan() to get all the testcases unter the plan  I specified, but I have a question ,how to only run failed  and cases that have not been executed? for exampleI have run a test, which  inclued 330 cases, 300   passed, 20 failed ,and 10 have not been execued. I want to run the test again, but only run the 30 which  are not passed, how can I do this in my code ?

**Comment by lczub** [comment]
Hello CamilleDZ,

I guess following should extract you all tests, which have currently a failed status
`myTestLink.getTestCasesForTestPlan(newTestPlanID_A, executestatus='f')`

you can find additional samples of using _getTestCasesForTestPlan_ in [example/TestLinkExample.py](https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExample.py)

Regards Luiko

**Comment by lczub** [comment]
No additional feedback
