### ISSUE TITLE
Provide timeout option in connect() method under testlinkhelper class

### ISSUE THREAD

**Issue by chintanvadgama** [lczub/TestLink-API-Python-client#102]
It would be great to have connection timeout option in connect method

**Comment by lczub** [comment]
Hello Chintan Vadgama ,
this is a duplicate of your former question #87. Unfortunately, I closed it, cause you give no feedback to my response https://github.com/lczub/TestLink-API-Python-client/issues/87#issuecomment-294961761.

The situation is still unchanged. To solve this, I need support maybe from you or someone else you know to investigate time in finding a solution. Do you think, this is possible?

Regards Luiko

**Comment by lczub** [comment]
No additional feedback
