### ISSUE TITLE
raise 500 Internal Server Error

### ISSUE THREAD

**Issue by wangrocky** [lczub/TestLink-API-Python-client#104]
I tried this:
tls.reportTCResult(206955, 'p', testcaseid=196925, buildname='', notes='', user='', platformid=None)
and i got ：
raceback (most recent call last):
  File "testlinkTrial.py", line 81, in <module>
    report_test_result(206955, 196925, 'p')
  File "testlinkTrial.py", line 60, in report_test_result
    testcaseexternalid=test_case_id, platformname="")
  File "C:\Python27\lib\site-packages\testlink\testlinkdecorators.py", line 112, in wrapperAddDevKey
    return methodAPI(self, *argsPositional, **argsOptional)
  File "C:\Python27\lib\site-packages\testlink\testlinkdecorators.py", line 100, in wrapperWithArgs
    *argsPositional, **argsOptional)
  File "C:\Python27\lib\site-packages\testlink\testlinkapigeneric.py", line 1517, in callServerWithPosArgs
    response = self._callServer(methodNameAPI, argsOptional)
  File "C:\Python27\lib\site-packages\testlink\testlinkapigeneric.py", line 1996, in _callServer
    raise testlinkerrors.TLConnectionError(new_msg)
**testlink.testlinkerrors.TLConnectionError: problems connecting the TestLink Server http://myip:8080/testlink/lib/api/xmlrpc/v1/xmlrpc.php
<ProtocolError for myip:8080/testlink/lib/api/xmlrpc/v1/xmlrpc.php: 500 Internal Server Error**>

**Comment by lczub** [comment]
Hello wangrocky,

you tried to report a test result without any build information.

The wiki page [Usage](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/usage.rst#report-test-results) describes, how you can report results.

The samples[TestLinkExample.py](https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExample.py) and   [TestLinkExampleGenericApi](https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExampleGenericApi.py) includes several variation how _reportTCResult_ can be used.

Hope this helps, regards Luiko

**Comment by lczub** [comment]
No additional feedback
