### ISSUE TITLE
Run TestLinkExample.py display  "problems calling the API method setTestCaseTestSuite"

### ISSUE THREAD

**Issue by reynold6215** [lczub/TestLink-API-Python-client#106]
[error.log](https://github.com/lczub/TestLink-API-Python-client/files/2158843/error.log)

My TestLink version 1.9.14 

Cannot work move test case TC_B to correct test suite B function
Code:
tc_b_full_ext_id = myTestLink.getTestCase(newTestCaseID_B)[0]['full_tc_external_id']
response = myTestLink.setTestCaseTestSuite(tc_b_full_ext_id, newTestSuiteID_B)
print("setTestCaseTestSuite TC-B to TS-B" , response)

Display Error message:
**New Test Case 'TESTCASE_B' - id: 853**
Traceback (most recent call last):
  **File "example/TestLinkExample.py", line 287, in <module>
    response = myTestLink.setTestCaseTestSuite(tc_b_full_ext_id, newTestSuiteID_B)**
  File "/root/.pyenv/versions/testlink-env1/lib/python2.7/site-packages/testlink/testlinkdecorators.py", line 112, in wrapperAddDevKey
    return methodAPI(self, *argsPositional, **argsOptional)
  File "/root/.pyenv/versions/testlink-env1/lib/python2.7/site-packages/testlink/testlinkdecorators.py", line 100, in wrapperWithArgs
    *argsPositional, **argsOptional)
  File "/root/.pyenv/versions/testlink-env1/lib/python2.7/site-packages/testlink/testlinkapigeneric.py", line 1517, in callServerWithPosArgs
    response = self._callServer(methodNameAPI, argsOptional)
  File "/root/.pyenv/versions/testlink-env1/lib/python2.7/site-packages/testlink/testlinkapigeneric.py", line 2000, in _callServer
    **raise testlinkerrors.TLAPIError(new_msg)**
**testlink.testlinkerrors.TLAPIError: problems calling the API method setTestCaseTestSuite
<Fault -32601: 'server error. requested method tl.setTestCaseTestSuite does not exist.'>**
(testlink-env1) root@TestLink-Auto:~/test1#

**Comment by lczub** [comment]
Hello reynold6215,

the API method _setTestCaseTestSuite_ is only available with a TestLink server version 1.9.17 - see   [CHANGES.rst v0.8.0](https://github.com/lczub/TestLink-API-Python-client/blob/master/CHANGES.rst#testlink-api-python-client-v080-may-2018).

The latest Testlink client version, supporting your TestLink server version 1.9.14 is [TestLink-API-Python-client v0.6.2](https://github.com/lczub/TestLink-API-Python-client/blob/v0.8.0/CHANGES.rst#testlink-api-python-client-v062-release-notes-v062-oct-2015).

Hope, this helps. Regards Luiko

**Comment by reynold6215** [comment]
Hi Luiko

Thank your help.
After evaluation, I will upgrade the version of testlink v1.9.17 and try the sample program again.
Because the new testlink interface and features are better.

Reynold
