### ISSUE TITLE
Automatically set the step status in a testcases

### ISSUE THREAD

**Issue by loicmbakop** [lczub/TestLink-API-Python-client#107]
Hello, I am working on a test automation project, and I am new to testlink. The tools i use for my project are the following
- Testlink 1.9.17.
- Testlink Python API version 1.1
- Jenkins version 2.107.3
I am using the python api to read steps of each tests cases of a testpan and execute some actions. What i need to do is to be able to set the status of each step in a test case, and in the python api I have not seen any method that allow me to do that.

In other words The method reportTCResult only allow me to set the status of a test case and to manually set the status each step like this 
newResult = myTestLink.reportTCResult(None, newTestPlanID_A, None, 'f', '', guess=True,
                                      testcaseexternalid=tc_aa_full_ext_id,
                                      platformname=NEWPLATFORM_A,
                                      execduration=3.9, timestamp='2015-09-18 14:33'
                      steps=[  {'step_number' : 6, 'results' : 'p', 'notes" : 'result note for passed step 6'}, 
                                   {'step_number' : 7, 'results' : 'f', 'notes" : 'result note for failed step 7'}]  )
 Using that method i need to know how much steps i have in my test case. What i would like to do is to automate that by setting the status of each of my steps first during the execution, and depending on that, set the status of the test case. I have not seen any method to do that in the python api and i am currently stucked. 

Thank you for your help

**Comment by lczub** [comment]
Hello loicmbakop,

you are right, the testlink server itself only provides *reportTC* to set the state for test steps, it does currently not support to set a single step result - see TestLink Github [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php#L8572]).
So if you require such a method, you first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method , the API python client could use this.

But I have a problem, to understand your requirement, cause methods like *getTestCasesForTestSuite* and *getTestCase* returns a list with all test steps. So you are able to know, how many steps a test case has.

And you have to cache the history of executed steps in any way to decide at the end , if the test case passed or failed. So the step state info should be there, or?

Keep in  mind, each single request to the server increase your network traffic and creates a separate database request. That might be a time factor, what can slow done your test duration.

And when your steps so complex, that you requires a separate state commit, is this step maybe an own test case?

Hope this help you to come to a better automation design.

Regards Luiko

**Comment by loicmbakop** [comment]
Hi, 
Thank you very much for your answer. Yes in my python script i acually use the method getTestCAseForTestSuite to extract the informations about actions and the expected result of each steps, and also i count the number of steps in my testcase. What i am doing for my requirement is the following. Based on what i read on the step action part of my step, my script is going to call some other bash script to execute different operations, to command and elevator. For exemple if my first step action is sendATo 5, i will call a bash script that execute that operation to send the elevator to the 5th floor on my system, and at the end i want to be able to set the status  of the step as passed or fail in my python script. 
I dont fully understant when you say " you have to cache the history of executed steps in any way to decide at the end , if the test case passed or failed. So the step state info should be there, or?" Can i do that using the python api in my python script ?

**Comment by lczub** [comment]
Hello,
as mention, when your controlling python method is not able to cash the results of the executed bash scripts, you should think about, iif executing a bash script is maybe already a single test and not just a step.

Alternative approach : instead jenkins plus TestLink and own written python code, ever tried keyword and test data driven testing with _http://robotframework.org/_ .? Can make tester life much easier and avoid handling with server stuff.

Regards Luiko

**Comment by loicmbakop** [comment]
Thank you for your reply, but i have been working with testlink and jenkins for over a month now, and i already have most of my functions developped. I went on the mantis website to get some help and one admin added that functionnaly on the php side, and could not help me with the python API. Do you know who i should contact to have some help on the python side ? 

Regards loicmbakop

**Comment by lczub** [comment]
Helllo loicmbakop,

I guess, you are talking about [Mantis TL 8331](http://mantis.testlink.org/view.php?id=8331)
- [API - XMLRPC] add a new method to allow user to set the step result of a step in a test case using the xmlrpc api.

I will try out, if I can created an implementation during the next days on the python side.
Till then,
Luiko

**Comment by lczub** [comment]
Helllo loicmbakop,

with [Mantis TL 8331](http://mantis.testlink.org/view.php?id=8331) fman implemented a fix for *reportTC*, that if it is called with *overwrite=True*, adding / changing single step results without sending all prio reported step results is now supported. 
Cause the api itself (method name and method parameter) have not changed, you required no additional python changes. Please conside, you have always to commit a 'status' value for the test case.


`firstStepResult = myTestLink.reportTCResult(None, aTPlanID, aBuildName, 'p', 
                                      'first reportTC call for setting step result',                                   
                                      testcaseexternalid=aTCaseFullExID, 
                                      overwrite=False,
                                      platformname='Small Birds', 
                                      execduration='1.2',
                                      timestamp='2018-07-22 22:47',
                                    steps=[{'step_number' : 1, 'result' : 'p', 
                                            'notes' : 'passed first step result, important use overwrite FALSE, otherwise last execution will be changed'}]
                                      )
print ("reportTCResult first step", firstStepResult )

secondStepResult = myTestLink.reportTCResult(None, aTPlanID, aBuildName, 'p', 
                                      'second reportTC call for setting step result',                                   
                                      testcaseexternalid=aTCaseFullExID, 
                                      overwrite=True,
                                      platformname='Small Birds', 
                                      execduration='2.2',
                                      timestamp='2018-07-22 22:48',
                                    steps=[{'step_number' : 2, 'result' : 'p', 
                                            'notes' : 'passed second step, important use now overwrite TRUE, otherwise new TC execution will be created'}]
                                      )
print ("reportTCResult second step", secondStepResult )

thirdStepResult = myTestLink.reportTCResult(None, aTPlanID, aBuildName, 'p', 
                                      'third reportTC call for setting step result',                                   
                                      testcaseexternalid=aTCaseFullExID, 
                                      overwrite=True,
                                      platformname='Small Birds', 
                                      execduration='3.2',
                                      timestamp='2018-07-22 22:49',
                                    steps=[{'step_number' : 3, 'result' : 'f', 
                                            'notes' : 'failed third step, attention tc status is still set to passed'}]
                                      )
print ("reportTCResult third step", thirdStepResult )
`

Regards Luiko

**Comment by loicmbakop** [comment]
Hi Luiko, So if i understand, the correct way to set all my step would be to call the reportTCresult method, with the overwrite option = False for my first step and true to my next steps. Also I dont understand the nature of your 5th parameter in each of your call, when you put 'first reportTC call for setting step result'.
Today i tried to use the python api one more time to set each of my step status. I tried to use the overwrite option, but for all my steps and it did not work 

Regards Loicmbakop

**Comment by loicmbakop** [comment]
Hello,
I tried to call the method ReportTCResult the way you recommanded with overwrite=False for my first step, and True for my other steps, and i have only one report generated containing only my first step status and execution note set. But now whether i use the overwrite option at true or false i only have one report generated but with only one step set. 
- When i use overwrite=true/false for all my steps, i only get one report with my last step status and note set in my report
- When i use the overwrite= true for my first step and false for my next steps, i end up with one report with only my first step status and notes set

**Comment by lczub** [comment]
Hello Loicmbakop

>  I dont understand the nature of your 5th parameter in each of your call, when you put 'first reportTC call for setting step result'.

The 5th parameter is the note which will be attached to the test execution. You will see, it is always replaced with the latest note . Hint, use *whatArgs* do query, which maandatory parameter an api expects and which optional parameter are supported:

`print ( myTestLink.whatArgs("reportTCResult") )`

**Comment by lczub** [comment]
Hello  Loicmbakop,

with the samples I send 2 days ago (they uses the TestlinkAPIClient python class) and updating the TestLink Server php code to the commit state

`d05548c9d #0008331: XML-RPC API - reportTCResult() with overwrite on test case steps execution result`

I was able to create a test execution step by step sending single step results with *reportTC*, (first overwrite=False, the others with overwrite=True).

This is sample of the resulting test execution
![reporttc-singlesteps-result_2018-07-25](https://user-images.githubusercontent.com/1565880/43223269-d5039920-9052-11e8-8d6a-90b714b43a5a.png)

**Comment by loicmbakop** [comment]
Yes i can see that it worked fine for you. To take in account the modification that fman added on the php code, do i need to do some other type of change on my testlink installation ?

**Comment by loicmbakop** [comment]
Hello, 
By taking a second look at what you said I just saw that I needed to update my testlink server php code. Can you pls tell me which file i should modify 

regards loicmbakop

**Comment by loicmbakop** [comment]
Hi, I added the file clientTestExecStepsIncremental.php in the right repository and also i replaced the file xmlrpc.class.php in the V1 repository but it still dont work like for you

**Comment by loicmbakop** [comment]
Hello, it work now i did no work before because i added the new file to update my testlink in the wrong testlink reporsitory version. Thank you very much for your support 

regards loicmbakop
