### ISSUE TITLE
Executing the program in the example directory has functions that cannot be used.

### ISSUE THREAD

**Issue by reynold6215** [lczub/TestLink-API-Python-client#109]
Dear Sir,

The program I executed in the example directory has functions that cannot be used, and the functions cannot be executed as listed below. Error messages in execution such as attachments.

Do I have an execution order error or do I have to adjust it?

Execution environment:
Ubuntu 16.04, Python 2.7.15, TestLink V1.9.17, TestLink API 0.8

Execution order
TestLinkExample.py -->TestLinkExampleGernericApi.py --> TestLinkExampleGernericApi_Req.py --> TestLinkExample_CF_KW.py

- TestLinkExample.py
1.Get bug ID.
2.Copy test case - as a new TC version.
3.Get the different TC versions
4.Copy test case - as new TC in a different TestSuite 

- TestLinkExampleGernericApi.py
1.Get bug ID.

- TestLinkExampleGernericAPi_Req.py
1.Get all requirement for testprojekt
2.Add requirement reqA to testcase B
3.Get coverage for requirements reqA
4.add png file as Attachemnt to a requirement specification.
5.add png file as Attachemnt to a requirement.
6.update CustomField Value - TestCase SpecDesign 
7.get CustomField Value - TestCase SpecDesign
8.update CustomField Value - TestSuite SpecDesign
9.get CustomField Value - Requirement Specification
10.update CustomField Value
11.update CustomField Value - Build

- TestLinkExample_CF_KW.py 
1.return keyword list for TestCase_B
2.return keyword list for TestCase_AA
3.update CustomField Value - TestCase SpecDesign
4.get CustomField Value - TestCase SpecDesign
5.update CustomField Value - TestSuite SpecDesign
6.update CustomField Value

Reynold 
[error-information-log.txt](https://github.com/lczub/TestLink-API-Python-client/files/2208544/error-information-log.txt)

**Comment by lczub** [comment]
Hello Reynold,

this comment is related to the *getAllExecutionsResults* error messages:

reason for the *getAllExecutionsResults* errors is, that the TestLink V1.9.17 server itself has a known Bug [TL Mantis Ticket 8259](http://mantis.testlink.org/view.php?id=8259), documented inside [TestLink python API 0.8 CHANGES.rst](https://github.com/lczub/TestLink-API-Python-client/blob/v0.8.0/CHANGES.rst#known-tl-1917-issues )

I was unsure, if I should publish TestLink python API 0.8 supporting *getAllExecutionsResults* or not. But a fix is already publish inside the TestLink repository and you can easily implement it , by just extending inside _lib/api/xmlrpc/v1/xmlrpc.class.php_ the function _function initMethodYellowPages()_ with
`'tl.getAllExecutionsResults' => 'this:getAllExecutionsResults',` 

Alternative is, not to call *getAllExecutionsResults*, when using the published TestLink V1.9.17 version

Regards Luiko

**Comment by lczub** [comment]
Samples _TestLinkExample.py_ and _TestLinkExampleGernericApi.py_ have no preconditions and should work independently . Please try with commenting out the *getAllExecutionsResults* calls.
- I use these sample after each code change and they work currently in my environment

Samples _TestLinkExample_CF_KW.py_ and _TestLinkExampleGenericApi_Req.py_ includes at the top instructions, which sample must run before and which additional files have to be loaded.
- cause of the more complex preconditions, these sample have more an experimental state
- even while the api not supports to create such data (custom keywords, requirements) , just to query them

Hope, this info helps a little bit

Regards Luiko

**Comment by reynold6215** [comment]
Dear Luiko,

Thank you for your explanation and assistance. After I made the relevant corrections according to your instructions, the situation is as follows:

1) TestLinkExample.py  --> Have some error.(copy test case - as a new TC version is fail)
                 # copy test case - as a new TC version
                 #print("create new version of TC B")
                 #response = myTestLink.copyTCnewVersion(newTestCaseID_B, 
 Line 721  #                summary='new version of TC B', importance='1')
                #print('copyTCnewVersion', response)

Test log:
   create new version of TC B
Traceback (most recent call last):
  File "TestLinkExample.py", line 721, in <module>
    summary='new version of TC B', importance='1')
  File "/root/.pyenv/versions/env/lib/python2.7/site-packages/testlink/testlinkapi.py", line 189, in copyTCnewVersion
    duplicateaction = 'create_new_version')
  File "/root/.pyenv/versions/env/lib/python2.7/site-packages/testlink/testlinkapi.py", line 258, in _copyTC
    origArgItems['testprojectid'] = self.getProjectIDByNode(origTestCaseId)
  File "/root/.pyenv/versions/env/lib/python2.7/site-packages/testlink/testlinkapi.py", line 166, in getProjectIDByNode
    node_path = self.getFullPath(int(a_nodeid))[a_nodeid]
KeyError: 754

2) TestLinkExampleGernericApi.py          -->Normal execution 
3) TestLinkExampleGernericApi_Req.py  -->Normal execution
4) TestLinkExample_CF_KW.py                -->Normal execution

Do I have other areas that need to be modified to make the program work properly?

Regards Reynold

**Comment by lczub** [comment]
copyTCnewVersion is a helper method, which combines several api methods.
TestLinkExampleGernericApi.py shows, that the api methods itself works, but some unexpected data situation occurs when calling getFullPath in copyTCnewVersion. 
For debugging it would be helpful, when you add an additional print statement _print( self.getFullPath(int(a_nodeid)) )_ before calling _node_path = self.getFullPath(int(a_nodeid))[a_nodeid] _
Regards Luiko

**Comment by reynold6215** [comment]
Dear Sir,

Thank you for your explanation. Sorry, I will return to you now.
I will try the part you explained again.

Reynold
