### ISSUE TITLE
[Question] How to submit a carriage return '\n' on a note on test result ?

### ISSUE THREAD

**Issue by eskignax** [lczub/TestLink-API-Python-client#110]
Hello, I would like to send multiline notes for testcase result when I use automation.

This currently doesn't work:

`>>> import testlink
>>> tls = testlink.TestLinkHelper().connect(testlink.TestlinkAPIClient)
>>> tls.reportTCResult(a_TestCaseID, a_TestPlanID, 'a build name', 'f',
                       'note 1st line \n note 2nd line',
                       user='a user login name', platformid=a_platformID)`

I also tried with `<br \>` without better success (result still in one line ).

Any idea ?

Thank you.

**Comment by eskignax** [comment]
I tried again today, and now it's work correctly with **\n**
I have no idea why it couldn't work before.
I am closing the issue. Thanks.

**Comment by lczub** [comment]
Hello eskignax,
sorry for the late repsonse, but good to see, that you was able to solve the issue .
regards Luiko
