### ISSUE TITLE
testlink/lib/api/xmlrpc/v1/xmlrpc.php was not found

### ISSUE THREAD

**Issue by NEOOOOOOOOOO** [lczub/TestLink-API-Python-client#113]
I got below response when visit http://{YOURSERVER}/testlink/lib/api/xmlrpc/v1/xmlrpc.php

```
Not Found
The requested URL /testlink/lib/api/xmlrpc/v1/xmlrpc.php was not found on this server.
```

Can you help for this?

Thanks.

**Comment by lczub** [comment]
Hello Neo,
thank for your request.
Your answer is correct, when testlink is the only running application on the (virtual) server. When several applications are running on one (virtual) server,  the url requires an additional namespace / alias as you see in me sample.
Regards Luiko
