### ISSUE TITLE
[Question]Where can I find the Testlink restful API doc?

### ISSUE THREAD

**Issue by mayzhou0401** [lczub/TestLink-API-Python-client#115]

**Comment by lczub** [comment]
Hello mayzhou0401,

this project handles with the XML-RPC api. How to get a list of supported XML-RPC api call see [How to talk with TestLink in a python shell](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/usage.rst#how-to-talk-with-testlink-in-a-python-shell).

For the restful api, I must guess. Think best approach is you take a like directly into the code in [tlRestApi.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/rest/v2/tlRestApi.class.php)

Hope this helps a little.
Regards Luiko

**Comment by lczub** [comment]
no further response
