### ISSUE TITLE
Can i get notes of each steps  after executing the test case?

### ISSUE THREAD

**Issue by chihuen** [lczub/TestLink-API-Python-client#117]
Can i get notes of each steps  after executing the test case?

**Comment by lczub** [comment]
Hello chihuem,

As I understand the TL Server XMLRPC Api [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php), two api methods _getExecutionSet()_ and _getLastExecutionResult()_ exist, which returns excution notes. But in both cases, just for the test case, not for a single steps. 

```
 * @return mixed $resultInfo
 *         if execution found
 *         array that contains a map with these keys:
 *         id (execution id),build_id,tester_id,execution_ts,
 *         status,testplan_id,tcversion_id,tcversion_number,
 *         execution_type,notes.
```

So if you require such a method, you first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method , the API python client could use this.

Hope, this helps a little bit.
Regards Luiko

**Comment by chihuen** [comment]
Thx for your replying ^_^
