### ISSUE TITLE
<type 'exceptions.AttributeError'>: 'module' object has no attribute 'TestlinkAPIClient'

### ISSUE THREAD

**Issue by wangmcyj** [lczub/TestLink-API-Python-client#118]
>>> help("testlink")
problem in testlink - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'TestlinkAPIClient'

**Comment by lczub** [comment]
Hello wangmcyj,

sorry for the late response. 
If I understand your short request right, you suggest, that the testlink-api should support the python build-in function [help](https://docs.python.org/3.7/library/functions.html#help), correct ? 

I have to check, what has to be changed.
In the meantime, you find a short documentation in [usage.rst](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/usage.rst)

Regards Luiko
