### ISSUE TITLE
[Question] Assign Requirements

### ISSUE THREAD

**Issue by Tahrky** [lczub/TestLink-API-Python-client#120]
Hi everyone (and @lczub)

I'm currently using the API to recopy a test case in a new test suite. 
When I use **_copyTCnewTestCase_**, I have the copy, but there is no requirements assign to it.

I think that i have to use the function **_assignRequirements_**, but I don't know how to get  _requirementsId_ and _requirementsSpecId_.

**_getRequirements_** give me all the requirementsId, but is that enough ? If yes, what id goes where ?

Thanks in anticipation of an answer,
Greetings.

**Comment by lczub** [comment]
Hello Tahrky,

thanks for your interesssting request.  
Unfortenatly, I have no much experiences with the requirement api functions, cause they look for me not fully implemented on the server side. You find your question also formulated by me in [TestLinkExampleGenericApi_Req.py](https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExampleGenericApi_Req.py)

``` 
Cause of missing knowledge, how ids of kind
- requirement and requirement specifications
- testplan - testcase link
could be requested via api, these example does not work currently.
```

I will do some tries over the weekend and if I find a way, I will inform you, ok?
Regards Luiko

**Comment by Tahrky** [comment]
Hello @lczub,

Thanks for your fast answer ! Yeah, i didn't found anything that could help me too to find how get it with the API. 
If I correctly understood, requirement specification is the category of the requirements, there is only one able at a time, and it could be as many requirements as we need.
I'm currently using your solution at work, it is a great tool but I'm constantly thinking that TestLink lack so much features (and I'm sure that's not because of you) that you have to build some strange things to do what you want.

Thanks you a lot for your help ! 
Have a nice day,
Greetings !

**Comment by lczub** [comment]
Hello Tahrky,

to fullfill your requirement, the TestLink server itself must be extended (or corrected).

Main pitfall is, that the api function _assignRequirements_ requires the *id* of an requirements and the *srs_id* of the related req_spec. Problem is, the api function _getRequirements_ only returns the requirement ids. 

Change request against TestLink Server would be, that _getRequirements_ should also return the *srs_id* or _assignRequirements_ should work without *srs_id*.

Without this extension, you will have to combine the python api client with direct database interactions.

So if you create a change request for the TestLink server ( [Mantis TestLink](http://mantis.testlink.org/view_all_bug_page.php) ) , that the srs_id can be requested via the api, I could extend afterwards the python client .

The workflow on the client side might be
- get list with all requirements of a project - _myTestLink.getRequirements(aTProjectID)_
- loop over all requirements and cache for each of them the related test cases - _myTestLink.getReqCoverage(aTProjectID, reqA['req_doc_id'])_
- loop over your test cases, which you have used as base of the copys and check, if they are referenced by one or more of the above requirements
- assign these requirements to your new test case copys, using _assignRequirements_ (only possible, when the srs_id is known)

Another new helpful TestLink server function would be the inverse of _getReqCoverage_, returning all requirements (or id and srs_id) assigned to a test case. That would reduce the client side workflow, specially the caching of req - tc references.


Regards Luiko

**Comment by Tahrky** [comment]
Hello @lczub,

Thanks again for your fast answer. 

Well, you explain very well all the steps to have a result, but the problem is that I have only few days on this project, because it was a temporary project while I was waiting for one more important to begin. 

I don't think that I will obtain a solution to my answer before one or two days (because I think after this, this project will be over), but if you think that it will be helpful for you in the future, I still can try to make a request so they will add it in the features.

Thanks you for all your help.
Greetings !

**Comment by lczub** [comment]
Hello Tahrky,
I undertand your time problem. It would be great, when you find time to open the request agains the TL server. 
It's always good, when request are open from different people to show, that the xmlrpc api is used by several user groups.

Regards Luiko

**Comment by Tahrky** [comment]
Hi @lczub,

I made an issue : http://mantis.testlink.org/view.php?id=8709 
Hoping that will help you in your work ;).

Have a nice day !
Greetings.
