### ISSUE TITLE
how to pass the arguments  of 'executestatus = 'n'' to function getTestCasesForTestPlan

### ISSUE THREAD

**Issue by CarrieSun** [lczub/TestLink-API-Python-client#123]
when I execute the following functions in pycharm ,
`response = my_testlink.getTestCasesForTestPlan(testplanid=test_plan_id, buildid=build_id, platformid=platform_id, executestatus="n")`
 
the response is [],  an empty array, but actually, I have a lot of unexecuted test cases.  I want to get those unexecuted test cases information.

**Comment by CarrieSun** [comment]
if  executestatus="a" , the response is an empty array too ,actually it is not empty.

**Comment by lczub** [comment]
Hello CarrieSun,

good question!

Unfortunately, the TestLink Server itself has not documented this case.
The state 'n' returns nothing, while 'f' and 'p' works.
As first response I would say, get all test cases and use python to filter them.

If you want to let the server do this, the answer might requires a deep dive into the TestLink Server code, somewhere in _testlink_code/lib/functions/testplan.class.php_ 

- function [initGetLinkedForTree](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/54170449bbc61af2847518264cb7a2591dd749a4/lib/functions/testplan.class.php#L6172)
- function [getLinkedTCVersionsSQL](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/54170449bbc61af2847518264cb7a2591dd749a4/lib/functions/testplan.class.php#L6902)
- function [getLTCVNewGeneration](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/54170449bbc61af2847518264cb7a2591dd749a4/lib/functions/testplan.class.php#L6814)

If you find a solution, it would be fine if you share it with the other user.
I will do some tries at the weekend. 

Regards Luiko

**Comment by CarrieSun** [comment]
Hello  Luiko,
Thank you very much for your fast and detailed answer ! 

Have a nice day !
Greetings.
