### ISSUE TITLE
How can i get the test case relations?

### ISSUE THREAD

**Issue by Earrow** [lczub/TestLink-API-Python-client#124]

**Comment by lczub** [comment]
Hello Earrow,
a little bot more description would be helpful to understand your requirement.
Which relations, you see inside the TestLink Web Client, do you want to get data for?
Regards Luiko

**Comment by Earrow** [comment]
Hi Luiko,

Thanks for the response. I just want to get the data of test case relations as shown in the picture:
![image](https://user-images.githubusercontent.com/13507166/65003757-64890300-d92c-11e9-96a7-aa113ad7d3c2.png)

When i export test suite to a xml file, the relations data is in the 'relation' node:
`<relation>
	<source>tyjrpt-gs-56574</source>
	<destination>tyjrpt-gs-56573</destination>
	<type>3</type>
</relation>
`

But when i use the api 'getTestSuiteByID', there is no relations data, so how can i get it?

**Comment by lczub** [comment]
Hello Earrow,

it looks, as if the Testlink server itself does not deliver these relation data via the xmlrpc api.

I can not find inside https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php any method , comment or content, referencing such relation / source /destination data. 

This client can only return data, the server deliver via the xxmlrpc api.
Sorry, regards Luiko

**Comment by Earrow** [comment]
That's ok, thanks anyway.
