### ISSUE TITLE
Could you pls help to provide the way to export testcase or project by testlink api? Thanks

### ISSUE THREAD

**Issue by tojoykorea** [lczub/TestLink-API-Python-client#132]
I can export 58 testcases on testlink web page, but when I export more to 76 testcases,it return blank page with error--500 Internal Server Error [http://testlink.mytesthost.com/lib/testcases/tcExport.php]
so I want to try if the testlink api can export more testcases success, which just for the same to tcExport.php?

**Comment by lczub** [comment]
Hello tojoykorea,

please apologize the late response.

Currently, no api (helper) method exist to export test cases from one database and to import them into another one. Maybe following works
- connect to TL server A
- get dictionary with existing test cases of an existing test plan - *getTestCasesForTestPlan* with optional argument *getstepinfo* 
- or get list with existing test cases of an existing test suite - *getTestCasesForTestSuite* with argument *details* set to *full*
- export list / dictionary to a json file using *json.dump()* - see [Stackoverflow - How do I write JSON data to a file?](https://stackoverflow.com/questions/12309269/how-do-i-write-json-data-to-a-file) 
- close connection to TL server A and connect to TL server B (or other system)
- import json file using *json.load()*, parse  list / dictionary structure and create new test cases / suite / project  

Problem:
- This will export only internal ids for references like platforms, builds ...
 
Details about the api methods return values see samples and comments in [TestLinkExample.py](https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExample.py) .

If you want to copy the test cases just inside the same database, maybe the TestlinkAPIClient method *copyTCnewTestCase()* helps, see [usage - Copy Test Cases](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/usage.rst#copy-test-cases) .

Possible workflow might be
- Create new test plan + test suite (createTestPlan, createTestSuite)
- loop over existing test cases of existing test plan or test suite (getTestCasesForTestPlan, getTestCasesForTestSuite)
- call for each existing test case *copyTCnewTestCase()* with existing *testcase_id* and new *testsuiteid*


Hope this helps a little bit.
Regards and stay healthy
Luiko
