### ISSUE TITLE
assignRequirements

### ISSUE THREAD

**Issue by vladhategancs** [lczub/TestLink-API-Python-client#135]
Hi, I am trying to use the assignRequirements exactly as you stated in the examples from APIGeneric, but whatever I do I get an xmlparse error: "junk after document element: line 1, column 91". 

I found no way of passing an array of dictionaries to this method nor found examples on the internet or in the doc folder of this repo.

Can you help me?

**Comment by lczub** [comment]
Hello vldhategancs,

Getting a *xmlparse error: junk after document element* is often a symptom, that the TestLink server itself was running in an internal error and returns native error statements instead XML formatted messages.
You can do two things for further analyses

1. check our web server and TestLink logs for errors methods
2. enable the debug mode as described in [How to check original exchanged XML data](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/usage.rst#how-to-check-original-exchanged-xml-data)

Additional helpful information would be: 
- which TestLink Server Version are you using?
- which Testlink Python API Version are you using?

Regards Luiko

**Comment by vladhategancs** [comment]
Hello Luiko,

I will try the debug mode method you described above. 

Here are the additional info you required. Do you think it may be a version problem here?
TestLink-API-Python-client 0.6.4  
TestLink 1.9.16 (Moka pot)

Best,
Vlad

**Comment by lczub** [comment]
Hello Vlad,
TL 1.9.17 has added additional api methods *getRequirements* and *getReqCoverage*, which are supported with TestLink-API-Python-client 0.8.0. 

The problematic api method *assignRequirements* was already introduced with TL 1.9.8 and I haven't seen significant changes on it  and also doesn't find a working round trip to test them as mention in [TL Mantis CR 7914](http://mantis.testlink.org/view.php?id=7914).

Maybe I oversaw something. If you find a working parameter combination to call, I would be glad to extend the sample [TestLinkExampleGenericApi_Req.py](https://github.com/lczub/TestLink-API-Python-client/blob/941bb7eb3a456f737e0238329e4381081e736b1f/example/TestLinkExampleGenericApi_Req.py#L53) with it.

Please apologize, that I haven't a solution for you.
Regards Luiko

**Comment by vladhategancs** [comment]
Hello Luiko,

No problem, thank you for your answers. Really appreciate it!

All the best,
Vlad
