### ISSUE TITLE
New line is ignored while adding Test steps and Expected behavior in 'createTestCase' API

### ISSUE THREAD

**Issue by abhay2703** [lczub/TestLink-API-Python-client#137]
While adding test cases using TL API createTestCase, if a test case has multi line steps/expected behavior, then they are all added in a single line.
Which takes away the readability. 
Example:
```
StepsList = [{'step_number' : 1, 'actions' : "Step action 1 - long_B\nStep action 1 - long_B\nStep action 1 - long_B" ,
'expected_results' : "Step result 1 - long_B", 'execution_type' : 0},
{'step_number' : 2, 'actions' : "Step action 2 - long_B" ,
'expected_results' : "Step result 2 - long_B", 'execution_type' : 0}]
```
![Steps](https://user-images.githubusercontent.com/61310494/84150861-1ac6e680-aa80-11ea-8a4a-9f686935c153.PNG)

Is this expected behavior of the API?

**Comment by lczub** [comment]
Hello Abhay,
yes this is an expected behavior. As you may notice in #136, you can use HTML tags to format test case descriptions and it should also be usable for steps. The HTML tag `<br>` instead python line feed `\n` should add the wanted linefeed.
Regards Luiko

**Comment by abhay2703** [comment]
Dear Luiko,

Thanks for the solution. I didn't know about the limitation.

Regards,
Abhay
