### ISSUE TITLE
Function "assignRequirements" argument "requirements"

### ISSUE THREAD

**Issue by mbounabi** [lczub/TestLink-API-Python-client#142]
https://github.com/lczub/TestLink-API-Python-client/blob/3d4f7ac211576decc7f027d97250ef66b88b7a2b/src/testlink/testlinkapigeneric.py#L596
The argument "requirements" from the function "assignRequirements" requires a "req_spec" value. Currently, as written in the comment, the internal IDs must be known.
However, when looking at the following example:
https://github.com/lczub/TestLink-API-Python-client/blob/ab7176a793399a6776d1711877d1f92329b22558/example/TestLinkExampleGenericApi_Req.py#L243
the "req_spec" value should be available in the requirement object, with the key "srs_id".

Is the key "srs_id" planned to be added at some point?
Or, could it be possible to retrieve the "req_spec" value for the requirement in "assignRequirements" an other way?

**Comment by lczub** [comment]
Hello mbounabi,

discussion for questions #135 describes the current state. We have to wait for changes on the TL server site. This 
Sorry, Regards Luiko

**Comment by mbounabi** [comment]
Hello,

I didn't see the issue because it was already closed. The Mantis bug mentionned in that other issue hasn't moved since 2017 so I guess that there are very few chances to see the modifications on the server side...

Thanks for your feedback!

Regards
