### ISSUE TITLE
"removeTestCaseKeywords" and "addTestCaseKeywords" are throwing Fault -32601: server error

### ISSUE THREAD

**Issue by chaitugv** [lczub/TestLink-API-Python-client#144]
Hi,

Firstly, thank you so much for the Testlink API.
Few APIs like "removeTestCaseKeywords" and "addTestCaseKeywords" are throwing errors. Other API "getTestPlanByName" is working fine.

Keyword related APIs are throwing below errors, could you please help me with this issue, not sure the exact reason. 

Below are the issues:
================
tls.removeTestCaseKeywords({'83617' : ['Keword1']})
*** testlink.testlinkerrors.TLAPIError: problems calling the API method removeTestCaseKeywords

tls.addTestCaseKeywords({'83618' : ['Keyword2']})
*** testlink.testlinkerrors.TLAPIError: problems calling the API method addTestCaseKeywords
<Fault -32601: 'server error. requested method tl.addTestCaseKeywords does not exist.'>

Thanks a lot in Advance,
Chaitanya

**Comment by chaitugv** [comment]
My testlink version - 1.9.9(Lone Ranger)

**Comment by lczub** [comment]
Hello Chaitanya,

your older testlink server version 1.9.9 is the reason, why you got this error. 
A TL server version >= 1.9.13 (better 1.9.14) is required to use the api method *removeTestCaseKEywords*.

See [changes - implement 1.9.13 new api methods](https://github.com/lczub/TestLink-API-Python-client/blob/master/CHANGES.rst#implement-1913-new-api-methods-32-41-42-44-47-46) 

Regards Luiko

**Comment by chaitugv** [comment]
Thank you Luiko for the immediate response.
I will try these API methods after upgrading the Testlink.
