### ISSUE TITLE
Attachment File is not closed

### ISSUE THREAD

**Issue by quartoxuna** [lczub/TestLink-API-Python-client#148]
The file-like object used for uploaded attachments is never closed, which could be a security issue.
The object is opened and the data is read in **testlinkapigeneric._openAttachmentForRead**, but the file is never closed.

**Comment by lczub** [comment]
Moin Kai,

thanks for your task. I pushed a fix suggestion. 
Unfortunately, I have currently no working TestLink test env. Would be fine, when you can run a test.

Regards Luiko

**Comment by quartoxuna** [comment]
Hey Luiko,

I was able to verify the fix with a TestLink environment. Everything works as expected.

Thanks

**Comment by lczub** [comment]
Thanks kai,
I pushed it to master.
Cheers Luiko
