### ISSUE TITLE
How can I use this api to add, update and delete data 

### ISSUE THREAD

**Issue by BenHmidaMohammadAli** [lczub/TestLink-API-Python-client#156]
I am currently using Testlink 1.9.11 and I have difficulties to use the API for testlink. I searched on the web for similar issues but nothing helped.
I'm trying to use api to can add, update and delete data of test project from testlink database 
The first step is well done 
I create a connectio and get project which is in data base 
______________________________
tlsh = testlink.TestLinkHelper().connect(testlink.TestlinkAPIClient)
print (tlsh.countProjects() )
tlsh.listProjects() 
______________________________
But I had a problems how can I use this api to add, update and delete data
Thank you

**Comment by lczub** [comment]
Hello Mohammad,
you find a small collection with HowTos in https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/usage.rst.

Cause your current used TL server is a litte bit outdated with 1.9.11, not all available api might work - take a look in https://github.com/lczub/TestLink-API-Python-client/blob/master/CHANGES.rst - chapters reflects which TL-py-api release matches to with TL-Server.

The api itself can only provide functions, which the TL-Server allows

Hope this helps for as start point
Regards Luiko
