### ISSUE TITLE
Download the report results of the test plan

### ISSUE THREAD

**Issue by lv123123long** [lczub/TestLink-API-Python-client#158]
After all the results of our test cases are backfilled, we hope to have an API for downloading the excel version of the test plan report. This should be a very useful function, and it is convenient to send the test results to others. Thank you very much!

**Comment by lczub** [comment]
Hello beautifulfox,

I agree, it would be helpful to download the test plan report excel version. 

Unfortunately, the TestLink Server itself does not support such an API method - see TestLink Github [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9_20_fixed/lib/api/xmlrpc/v1/xmlrpc.class.php) (branch testlink_1_9_20_fixed)

You first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method, this API python client could use this.

Greetings Luiko
