### ISSUE TITLE
How can I update a testplan with testlink API?

### ISSUE THREAD

**Issue by mayzhou0401** [lczub/TestLink-API-Python-client#160]
Hi 
  I want to update testplan attribute like 'active', but I cannot find tesltink related API in the doc or in this client.
  Can you please help? Thanks.

**Comment by lczub** [comment]
Hello [mayzhou0401](https://github.com/mayzhou0401),

I agree, it would be helpful to change the testplan status via an api. 

Unfortunately, the TestLink Server itself does not support such an API method - see TestLink Github [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9_20_fixed/lib/api/xmlrpc/v1/xmlrpc.class.php) (branch testlink_1_9_20_fixed)

You first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method, this API python client could use this.

Greetings Luiko

**Comment by mayzhou0401** [comment]
Hi [lczub](https://github.com/lczub)

Thanks for the reply and the information, I will open an enhancement against TestLink later.
