### ISSUE TITLE
pip install fails under linux py26 (v0.6.1)

### ISSUE THREAD

**Issue by maafy6** [lczub/TestLink-API-Python-client#50]
```
$ python --version
Python 2.6.6

$ pip --version
pip 6.0.8 from /usr/lib/python2.6/site-packages (python 2.6)

$ pip install TestLink-API-Python-client
Collecting TestLink-API-Python-client
  Downloading TestLink-API-Python-client-0.6.1.zip (96kB)
    100% |################################| 98kB 888kB/s 
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-peUcFb/TestLink-API-Python-client/setup.py", line 13, in <module>
        version_code = compile(fpv.read(), 'version.py', 'exec
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-peUcFb/TestLink-API-Python-client/setup.py", line 13, in <module>
    
        version_code = compile(fpv.read(), 'version.py', 'exec
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-peUcFb/TestLink-API-Python-client
```

**Comment by lczub** [comment]
Hello Matt,

thanks for your bug report. It seams to be a linux py26 specific problem, which I currently not completely understand.

a) Win8.1 Py2.6.6 with pip 1.5.6 install works without error
b) debian Py 2.7.3 with pip 1.1 install works without error
c) debian Py 2.6.8 with pip 1.1 install reproduces your error

I will try to understand, what is going wrong.
Regards, Luiko

**Comment by lczub** [comment]
Hello Matt,

suggestion for a workaround, download the zip archive, unzip it, open setup.py in an editor

	wget -O TestLink-API-Python-client-0.6.1.zip http://sourceforge.net/projects/testlink-api-python-client/files/latest/download
	unzip TestLink-API-Python-client-0.6.1.zip
	cd TestLink-API-Python-client-0.6.1
	emacs setup.py

change setup.py 

	#with open(join(dirname(__file__), 'src', 'testlink', 'version.py')) as fpv:
	#    version_code = compile(fpv.read(), 'version.py', 'exec')
	#    exec(version_code)
	VERSION = '0.6.1'
	TL_RELEASE = '1.9.13'

and than installation should work with

	python setup.py install

Sorry, but I currently not see another solution

Regards, Luiko

PS: don't forget to install although *argparse* (see [Install - Preconditions](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/install.rst#preconditions))

**Comment by maafy6** [comment]
:+1: Thanks, the solution works well enough for now.

**Comment by lczub** [comment]
link to this workaround added in [Install - Known Installation Problems](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/install.rst#known-installation-problems)
