### ISSUE TITLE
whatArgs reports incorrect arg name for createTestCase

### ISSUE THREAD

**Issue by dmcbride64** [lczub/TestLink-API-Python-client#51]
whatArgs('createTestCase')

reports the following:

"createTestCase(<testcasename>, <testsuiteid>, <testprojectid>, <authorlogin>, <summary>, [steps=<steps>], [precondition
s=<preconditions>], [importance=<importance>], [execution=<execution>], [order=<order>], [internalid=<internalid>], [che
ckduplicatedname=<checkduplicatedname>], [actiononduplicatedname=<actiononduplicatedname>], [devKey=<devKey>])\n createT
estCase: Create a test case\n        positional args: testcasename, testsuiteid, testprojectid, authorlogin,\n
               summary\n        optional args : preconditions, importance, execution, order, internalid,\n
          checkduplicatedname, actiononduplicatedname\n                        \n        argument 'steps' will be set wi
th values from .stepsList, \n        - when argsOptional does not include a 'steps' item\n        - .stepsList can be fi
lled before call via .initStep() and .appendStep()\n        "

In particular, it says that `[execution=<execution>]`

However, when using `createTestCase` with this argument (e.g. `execution=2`), the test case was not set to 'Automated', as expected, although no error was reported and the test case was successfully created.  

After some searching and testing, I found that I could use `executiontype` instead of `execution` and I would get the result I was expecting.  Note that `executiontype` is not reported by `whatArgs`.

So, it seems likely that 'whatArgs` is reporting `execution` when it should be reporting `executiontype`

**Comment by lczub** [comment]
Hello dmcbride64,

thanks for this hint. Your are right, the argument name is *executiontype* and not *execution*.
Reason for this mistake is a wrong comment in testlink source code

compare [comment createTestCase](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php#L1991) and [constants $executionTypeParamName](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php#L144)

Your workaround to use *executiontype* is correct and I will implement it.

Regards Luiko
