### ISSUE TITLE
Delete Testcases?

### ISSUE THREAD

**Issue by TASSDevon** [lczub/TestLink-API-Python-client#52]
Is there a function to delete a testcase? I'd like to delete testcases with a specific word in the title.

**Comment by lczub** [comment]
Hello Devon,

unfortunately, TL itself does not provide an api method to detele testcases. 
(see [TL Githup xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php#L6990)).

What you can do is
a) deleting the test case steps via _deleteTestCaseSteps_ 
b) or updating the state of the test case via _updateTestCase_ to mark it as old / invalid

Regards, Luiko

**Comment by TASSDevon** [comment]
Ah I feared as much, I looked there and indeed, couldn't find it. It's weird there is support for deleting entire plans but not for testcases individually. Hopefully they'll add it in some future release.

Thanks for the fast reply!
