### ISSUE TITLE
How to Use this library with RobotFramework and can I use this with Jython?

### ISSUE THREAD

**Issue by ShilpaKuppelur** [lczub/TestLink-API-Python-client#57]
Hi,
I want to update Testcases status from my Testscripts which are written in Robotframework scripts So Can you please guilde me how to use this library

**Comment by lczub** [comment]
Moin ShilpaKuppelur,

as first step, please take a look into the example https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExample.py
It is also part of each release archive.

Run it with settings for your TestLink Installation. It will create a sample project with test cases , plans, builds and results.

I hope, that the comments and the run explains the fundamental handling.
Then we could discuss details, ok?

Greetings Luiko

**Comment by lczub** [comment]
closed caused by no additional feedback
