### ISSUE TITLE
how to assign test case to test plan

### ISSUE THREAD

**Issue by yarving** [lczub/TestLink-API-Python-client#65]
I need to assign a test case to a test plan, can you support it?

**Comment by lczub** [comment]
Hello Yarving,

take a look into  [TestLinkExample.py Line 268](https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExample.py#L268). This section explains the usage of _addTestCaseToTestPlan_ .
If you run this example against your TestLink application, it should create a sample project with test plan and execution results.

Hope this helps.
Regards Luiko

**Comment by yarving** [comment]
Thanks very much, got this question fixed.
