### ISSUE TITLE
I want to execute the case of first step

### ISSUE THREAD

**Issue by freetime312** [lczub/TestLink-API-Python-client#66]
hello Developer:
how to execute the case step by step and write back the result of every step

**Comment by lczub** [comment]
Hello Freetime312,

the current supported TestLink Release 1.14 itself does not support to set execution results step by step via the xml rpc api. 

But the current TestLink development release 1.15 seams to extend the api method reportTCResult(), see
- http://mantis.testlink.org/view.php?id=7313
-  https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/f8a25e414c33e93a5fcb6d1c2c1c68e1186b1cf1

If you have time, it would be helpful, when play around a little bit with that new TL function and maybe create an extension for TestLink-API-Python-client, which I can integrated.

I will have this time not before February .

Regards Luiko

**Comment by freetime312** [comment]
Hello Luiko:
could you please tell me how to conmunicate python and testlink with XMLRPC?

**Comment by lczub** [comment]
Hello freetime312,

When I understand the Testlink changes
- https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/f8a25e414c33e93a5fcb6d1c2c1c68e1186b1cf1#diff-7b68ef267ed1cf927e5e0287479480f0R2291

you have luck and need no code changes inside the python client. You just have to call reportTCresult() with an additional optional argument _steps_ .
Something like

```
newResult = myTestLink.reportTCResult(None, newTestPlanID_A, None, 'f', '', guess=True,
                                      testcaseexternalid=tc_aa_full_ext_id,
                                      platformname=NEWPLATFORM_A,
                                      execduration=3.9, timestamp='2015-09-18 14:33'
                      steps=[  {'step_number' : 6, 'results' : 'p', 'notes" : 'result note for passed step 6'}, 
                                   {'step_number' : 7, 'results' : 'f', 'notes" : 'result note for failed step 7'}]  )
```


General reportTCResult() examples see https://github.com/lczub/TestLink-API-Python-client/blob/master/example/TestLinkExample.py

Regards Luiko

**Comment by freetime312** [comment]
Hello Luiko:
thank you !
according to your instruction,my problem have been resolved. there is a litter problem, you should changed the 'results' to 'result'.
best Regards
