### ISSUE TITLE
How to create a requirement via the API ?

### ISSUE THREAD

**Issue by joelviel** [lczub/TestLink-API-Python-client#75]
Hi,

Is there any API function to create a requirement?
I only see functions to modify them: uploadRequirementAttachment or uploadRequirementSpecificationAttachment

Thank you for your help

**Comment by lczub** [comment]
Hello Joel,

currently it is not possible to create requirements and req. specifications using the Testlink XML-RPC API.

Reason is, that the TestLink Server itself does not support such an API method - see TestLink Github [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php]) 

You first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method , the API python client could use this.

Greetings Luiko

**Comment by joelviel** [comment]
Hi Luiko,

Thank you for this very clear answer and for your work :)

I will open an enhancement request for Testlink then.

**Comment by lczub** [comment]
Hello Joel,

FYI, the TL server future release 1.9.17 will support some new requirement api methods.
Details see [new api - getRequirements, getReqCoverage](https://github.com/lczub/TestLink-API-Python-client/issues/82)

I published the pre-release [v0.6.5-Alpha](https://github.com/lczub/TestLink-API-Python-client/releases/tag/v0.6.5-Alpha) , which should support this new methods.

Regards Luiko

**Comment by joelviel** [comment]
Thanks for this good news :)

**Comment by YPHFree** [comment]
can create a requirement via the API now? @lczub @joelviel

**Comment by lczub** [comment]
Hello YPHFree,
I'm sorry, but  I have not seen any additional requirement api functions since #82 
Regards Luiko
