### ISSUE TITLE
implement 1.9.17 new api - getExecutionSet

### ISSUE THREAD

**Issue by lijie-advantech** [lczub/TestLink-API-Python-client#76]
I only find a function named GetLastExecutionResult, but I can't get a testbulid execution result.

**Comment by lczub** [comment]
Hello lijie-advantech,

You are right, you detect a server site limitation. Currently it is not possible to ask for a complete build execution result, just single test case execution results using the Testlink XML-RPC API.

Reason is, that the TestLink Server itself does not support such an API method - see TestLink Github [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php#L7849) 

You first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method , the API python client could use this.

Greetings Luiko

**Comment by lczub** [comment]
TL future release 1.9.17 delivers a new api getExecutionResult

related TL Mantis Task 
- [7827](http://mantis.testlink.org/view.php?id=7827): [API - XMLRPC] Extend API to get ALL runs on a certain build - new function getExecutionResult (fman)

```
  /**
   * Gets a set of EXECUTIONS for a particular testcase on a test plan.
   * If there are no filter criteria regarding platform and build,
   * result will be get WITHOUT checking for a particular platform and build.
   *
   * @param struct $args
   * @param string $args["devKey"]
   * @param int $args["tplanid"]
   * @param int $args["testcaseid"]: Pseudo optional.
   *                 if is not present then testcaseexternalid MUST BE present
   *
   * @param int $args["testcaseexternalid"]: Pseudo optional.
   *                 if is not present then testcaseid MUST BE present
   *
   * @param string $args["platformid"]: optional. 
   *                    ONLY if not present, then $args["platformname"] 
   *                    will be analized (if exists)
   *
   * @param string $args["platformname"]: optional (see $args["platformid"])
   * @param int $args["buildid"]: optional
   *        ONLY if not present, $args["buildname"] will be analized (if exists)
   *
   * @param int $args["buildname"] - optional (see $args["buildid"])
   * @param int $args["options"] - optional 
   *                               options['getOrderDescending'] 
   *                               false(=ascending,default)
   * @return mixed $resultInfo
   *               if execution found
   *               array that contains a map with these keys:
   *               id (execution id),build_id,tester_id,execution_ts,
   *               status,testplan_id,tcversion_id,tcversion_number,
   *               execution_type,notes.
   *
   *               if test case has not been executed,
   *               array('id' => -1)
   * @access public
   */
  public function getExecutionSet($args)
```

**Comment by lczub** [comment]
Known TL issue: http://mantis.testlink.org/view.php?id=7900
