### ISSUE TITLE
Need feature to get metrics for reporting purposes

### ISSUE THREAD

**Issue by grushler** [lczub/TestLink-API-Python-client#78]
Hi, 

Currently under Test Reports section we can get reports for all the test plans. Can this feature be included in the api so that we can get reports from testlink and use it easily?

Thanks for your help!

**Comment by lczub** [comment]
Hello Girish,

I'm sorry, but as I know,  the TestLink Server itself does not support to deliver test reports through the XMLRPC  API - see TestLink Github [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php]) 

You first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method , the API python client could use this.

Reimplementing the test report generation on the Python client site by collecting all the data with several XMLRPC api calls makes no sense. Generation the test report is a server task.

Regards Luiko

**Comment by grushler** [comment]
Thanks Iczub 👍 Will open an enhancement ticket with Testlink.
