### ISSUE TITLE
Which method to use for update test execution to Pass, Failed or Blocked?

### ISSUE THREAD

**Issue by chintanvadgama** [lczub/TestLink-API-Python-client#86]

**Comment by lczub** [comment]
Hello Chintan,

I guess, _reportTCResult_ is the method you are searching for. You find a short description in [usage.rst - Report test results](https://github.com/lczub/TestLink-API-Python-client/blob/master/doc/usage.rst#id7) .

Regards Luiko

see

**Comment by lczub** [comment]
Response seams to help, cause no further comment
