### ISSUE TITLE
Please provide timeout() variable for connect() method

### ISSUE THREAD

**Issue by chintanvadgama** [lczub/TestLink-API-Python-client#87]
Testlink Server is setup on private IP & sometimes the IP is not reachable. So, could you please provide timeout variable by which it will stop reconnection attempts to the server. If it's already there then please do let me know.

**Comment by lczub** [comment]
Hello Chintan,

the testlink-api-python-client uses the [xmlrpclib](https://docs.python.org/2/library/xmlrpclib.html).
That doc says nothing about a timeout. So I have currently not an idea, how [TestlinkAPIGeneric._callServer()](https://github.com/lczub/TestLink-API-Python-client/blob/master/src/testlink/testlinkapigeneric.py#L1759) can notify timeout problems directly

There exists some older stackoverflow discussion which maybe help
- http://stackoverflow.com/questions/2425799/timeout-for-xmlrpclib-client-requests
- http://stackoverflow.com/questions/372365/set-timeout-for-xmlrpclib-serverproxy
- http://www.programcreek.com/python/example/682/xmlrpclib.ServerProxy

Have you the possibility to play around with your testlink-api-python-client to check, if one of this suggestions can solve your timeout problem?

The server is inititiales in [TestlinkAPIGeneric._init()](https://github.com/lczub/TestLink-API-Python-client/blob/master/src/testlink/testlinkapigeneric.py#L68)

Regards Luiko

**Comment by lczub** [comment]
Closed cause no additional required input
