### ISSUE TITLE
activate/inactive build, delete build

### ISSUE THREAD

**Issue by markkthemk** [lczub/TestLink-API-Python-client#91]
It is possible to use the webinterface to activate/deactivate builds, as well as delete builds. 
This is functionality that is missing in the API.

Keep up the good work!

**Comment by lczub** [comment]
Hello Mark,

currently it is not possible to update the active state of a build or delete it using the Testlink XML-RPC API. Just to set the active state during creation. 

Reason is, that the TestLink Server itself does not support such an API method - see TestLink Github [xmlrpc.class.php](https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php]) 

You first have to open an enhancement request against TestLink itself (http://mantis.testlink.org/login_page.php) for this topic. When TestLink server has implemented such an API method , the API python client could use this.

Regards Luiko

**Comment by lczub** [comment]
No additional feedback
