### ISSUE TITLE
How to use the tls.reportTCResult without "platformname"??

### ISSUE THREAD

**Issue by paulopimenta6** [lczub/TestLink-API-Python-client#98]
Hi Iczub,

I am using your API to connect Testlink to my PC and I have found a problem using it. So in my testcases created in Testlink I don't have plataforms. I tried to put platformname="None" or let it empty. 

Could you help me, please? If I don't use a platform in Testlink how I could run this part of code?

This is the parte I am trying:

>>> import testlink
>>> tls = testlink.TestLinkHelper().connect(testlink.TestlinkAPIClient)
>>> tls.reportTCResult(None, newTestPlanID_A, None, 'f', '', guess=True,
                       testcaseexternalid=tc_aa_full_ext_id, **platformname=NEWPLATFORM**_A,
                       execduration=3.9, timestamp='2015-09-18 14:33',
        steps=[{'step_number' : 6, 'result' : 'p', 'notes' : 'result note for passed step 6'},
               {'step_number' : 7, 'result' : 'f', 'notes' : 'result note for failed step 7'}]  )

Best Regards.

Paulo.

**Comment by lczub** [comment]
Hello Paulo,

the arguments _argname=_ are optional  arguments , so if you do not want to set them, just don't use them in your call. With _argname=NONE_ you explicite  set them to the value NONE.  In your sample, the solution should be 

```
import testlink
tls = testlink.TestLinkHelper().connect(testlink.TestlinkAPIClient)
tls.reportTCResult(None, newTestPlanID_A, None, 'f', '', guess=True,
testcaseexternalid=tc_aa_full_ext_id, 
execduration=3.9, timestamp='2015-09-18 14:33',
steps=[{'step_number' : 6, 'result' : 'p', 'notes' : 'result note for passed step 6'},
{'step_number' : 7, 'result' : 'f', 'notes' : 'result note for failed step 7'}] )
```
Ohter sample see [TestLinkExample.py - Line 485](https://github.com/lczub/TestLink-API-Python-client/blob/1a8b5d8ee642e83c44e474df947840d9ee12f045/example/TestLinkExample.py#L485)

Hope this helps,
Regards Luiko

**Comment by paulbodean88** [comment]
Hi Luiko,

Thanks for your reply, it works like this.

Best regards,
Paul

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
